import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

export const languages = [
  { code: 'es', label: 'Español' },
  { code: 'pt', label: 'Português' },
  { code: 'en', label: 'English' },
] as const

const resources = {
  es: { translation: {
    nav: { networks: 'Fuentes', validators: 'Validadores', transformers: 'Transformadores', actions: 'Acciones', runtime: 'Runtime', operation: 'Operación', harvesterAdmin: 'Cosechador', logout: 'Cerrar sesión' },
    common: { search: 'Buscar', state: 'Estado', all: 'Todos', save: 'Guardar', cancel: 'Cancelar', close: 'Cerrar', confirm: 'Confirmar', delete: 'Eliminar', parameters: 'Parámetros', configuration: 'Configuración', actions: 'Acciones', source: 'Fuente', action: 'Acción', worker: 'Worker', engine: 'Motor', loading: 'Cargando…', unavailable: 'No disponible' },
    login: { title: 'Cosechador', subtitle: 'Administración v5 de LA Referencia', description: 'Accede a la operación de fuentes, acciones y configuraciones de la instalación.', username: 'Usuario', password: 'Contraseña', submit: 'Ingresar', invalid: 'Las credenciales no son válidas o la API no está disponible.' },
    actions: { title: 'Acciones de la aplicación', activeEngine: 'Motor activo: {{engine}}', noActions: 'sin acciones descubiertas', refresh: 'Refrescar catálogo', loadError: 'No se pudo cargar el catálogo de acciones.', refreshSuccess: 'Catálogo actualizado: {{created}} nuevas, {{updated}} actualizadas, {{unavailable}} no disponibles.', key: 'Clave', workers: 'Workers', lastSeen: 'Última detección', enabled: 'Habilitada', workerConfigs: 'Configuraciones de workers', workerDescription: 'Parámetros globales de los workers. Se aplican a las nuevas ejecuciones de todas las fuentes.', workerLoadError: 'No se pudo cargar la configuración de workers.', disableTitle: 'Deshabilitar {{action}}', disableWarning: 'Se bloquearán las ejecuciones nuevas. Los procesos activos o en cola continuarán.', affected: '{{networks}} fuentes y {{schedules}} schedules están afectados.', globalConfig: 'Configuración global de {{worker}}', noParams: 'Este componente no publica parámetros configurables.', states: { ENABLED: 'Habilitada', DISABLED: 'Deshabilitada', UNAVAILABLE: 'No disponible', INVALID_CONFIGURATION: 'Configuración inválida' } },
    runtime: { title: 'Runtime', loadError: 'No se pudo obtener el estado del motor.', summary: 'Motor: {{engine}} · {{running}} procesos en ejecución · {{queued}} en cola', status: 'Estado', cancellation: 'Cancelación' },
    diagnostics: { title: 'Diagnóstico de fuente', noSnapshot: 'Esta fuente todavía no tiene un snapshot válido con información de diagnóstico.', back: 'Volver a fuentes', snapshot: 'Snapshot', filters: 'Los filtros afectan el resumen, las reglas y los registros.', search: 'Buscar identificador', validity: 'Validez', transformation: 'Transformación', failedRule: 'Regla fallida', all: 'Todos', valid: 'Válidos', invalid: 'Inválidos', transformed: 'Transformados', reset: 'Restablecer filtros' },
    networks: { center: 'Centro de operaciones', title: 'Fuentes cosechadas', subtitle: 'Supervisa resultados, programación y actividad en tiempo real.', sources: 'Fuentes', active: 'Activas', search: 'Buscar por acrónimo, repositorio o institución', loadError: 'No se pudieron cargar las fuentes.', inventory: 'Inventario de fuentes', results: '{{count}} resultado', results_plural: '{{count}} resultados', refresh: 'actualización automática cada 10 segundos', acronym: 'Acrónimo', repository: 'Repositorio', institution: 'Institución', latestSnapshot: 'Último snapshot', noSnapshots: 'Sin snapshots', edit: 'Editar fuente', editDescription: 'Los cambios se guardan de forma atómica, incluidas las asociaciones de procesamiento.', main: 'Principal', processing: 'Validación', profile: 'Datos específicos', actionSchedule: 'Acciones y programación', saveChanges: 'Guardar cambios', principalData: 'Datos principales y origen de cosecha', url: 'URL OAI-PMH', metadataPrefix: 'Metadata prefix', storageFormat: 'Formato de almacenamiento', sets: 'Sets OAI-PMH', cron: 'Cron de cosecha', validators: 'Validadores y transformadores', actionsOfSource: 'Acciones de esta fuente', acronymHelp: 'No se modifica para preservar la identidad de la fuente.', published: 'Fuente publicada', allSets: 'Añade uno o más setSpec; deja vacío para cosechar todos.', noSchedule: 'Expresión cron de seis campos; déjalo vacío para no programar la fuente.', processingRelations: 'Estas cuatro relaciones se actualizan junto al resto de la fuente.', manual: 'Permitir ejecución manual', scheduled: 'Ejecutar al dispararse la programación de la fuente', actionModifiers: 'Modificadores propios de cada acción', profileUnavailable: 'La fuente usa un perfil de atributos que no está publicado por esta instalación v5.', noPrevalidator: 'Sin prevalidador', noValidator: 'Sin validador', noTransformer: 'Sin transformador' },
    configuration: { reusable: 'Configuraciones reutilizables y sus reglas.', create: 'Crear {{kind}}', validator: 'validador', transformer: 'transformador', name: 'Nombre', description: 'Descripción', clone: 'Clonar', noItems: 'No hay configuraciones.', loadError: 'No se pudo cargar el listado.', deleteTitle: 'Eliminar {{name}}', deleteWarning: 'Esta acción eliminará la configuración y sus reglas.' },
  } },
  en: { translation: {
    nav: { networks: 'Sources', validators: 'Validators', transformers: 'Transformers', actions: 'Actions', runtime: 'Runtime', operation: 'Operations', harvesterAdmin: 'Harvester', logout: 'Sign out' },
    common: { search: 'Search', state: 'Status', all: 'All', save: 'Save', cancel: 'Cancel', close: 'Close', confirm: 'Confirm', delete: 'Delete', parameters: 'Parameters', configuration: 'Configuration', actions: 'Actions', source: 'Source', action: 'Action', worker: 'Worker', engine: 'Engine', loading: 'Loading…', unavailable: 'Unavailable' },
    login: { title: 'Harvester', subtitle: 'LA Referencia v5 administration', description: 'Access the operation of sources, actions and installation settings.', username: 'Username', password: 'Password', submit: 'Sign in', invalid: 'The credentials are invalid or the API is unavailable.' },
    actions: { title: 'Application actions', activeEngine: 'Active engine: {{engine}}', noActions: 'no discovered actions', refresh: 'Refresh catalog', loadError: 'Could not load the action catalog.', refreshSuccess: 'Catalog updated: {{created}} new, {{updated}} updated, {{unavailable}} unavailable.', key: 'Key', workers: 'Workers', lastSeen: 'Last detected', enabled: 'Enabled', workerConfigs: 'Worker configurations', workerDescription: 'Global worker parameters. They apply to new executions of every source.', workerLoadError: 'Could not load worker configurations.', disableTitle: 'Disable {{action}}', disableWarning: 'New executions will be blocked. Active or queued processes will continue.', affected: '{{networks}} sources and {{schedules}} schedules are affected.', globalConfig: 'Global configuration for {{worker}}', noParams: 'This component does not expose configurable parameters.', states: { ENABLED: 'Enabled', DISABLED: 'Disabled', UNAVAILABLE: 'Unavailable', INVALID_CONFIGURATION: 'Invalid configuration' } },
    runtime: { title: 'Runtime', loadError: 'Could not retrieve engine status.', summary: 'Engine: {{engine}} · {{running}} running processes · {{queued}} queued', status: 'Status', cancellation: 'Cancellation' },
    diagnostics: { title: 'Source diagnostics', noSnapshot: 'This source has no valid snapshot with diagnostic information yet.', back: 'Back to sources', snapshot: 'Snapshot', filters: 'Filters affect the summary, rules and records.', search: 'Search identifier', validity: 'Validity', transformation: 'Transformation', failedRule: 'Failed rule', all: 'All', valid: 'Valid', invalid: 'Invalid', transformed: 'Transformed', reset: 'Reset filters' },
    networks: { center: 'Operations center', title: 'Harvested sources', subtitle: 'Monitor results, scheduling and real-time activity.', sources: 'Sources', active: 'Active', search: 'Search by acronym, repository or institution', loadError: 'Could not load sources.', inventory: 'Source inventory', results: '{{count}} result', results_plural: '{{count}} results', refresh: 'automatic refresh every 10 seconds', acronym: 'Acronym', repository: 'Repository', institution: 'Institution', latestSnapshot: 'Latest snapshot', noSnapshots: 'No snapshots', edit: 'Edit source', editDescription: 'Changes are saved atomically, including processing associations.', main: 'Main', processing: 'Validation', profile: 'Specific data', actionSchedule: 'Actions and scheduling', saveChanges: 'Save changes', principalData: 'Source and harvest data', url: 'OAI-PMH URL', metadataPrefix: 'Metadata prefix', storageFormat: 'Storage format', sets: 'OAI-PMH sets', cron: 'Harvest cron', validators: 'Validators and transformers', actionsOfSource: 'Source actions', acronymHelp: 'Cannot be changed to preserve source identity.', published: 'Published source', allSets: 'Add one or more setSpec; leave empty to harvest all.', noSchedule: 'Six-field cron expression; leave empty to disable scheduling.', processingRelations: 'These four relations are updated with the rest of the source.', manual: 'Allow manual execution', scheduled: 'Run when the source schedule fires', actionModifiers: 'Action-specific modifiers', profileUnavailable: 'The source uses an attribute profile not published by this v5 installation.', noPrevalidator: 'No pre-validator', noValidator: 'No validator', noTransformer: 'No transformer' },
    configuration: { reusable: 'Reusable configurations and their rules.', create: 'Create {{kind}}', validator: 'validator', transformer: 'transformer', name: 'Name', description: 'Description', clone: 'Clone', noItems: 'No configurations.', loadError: 'Could not load the list.', deleteTitle: 'Delete {{name}}', deleteWarning: 'This action will delete the configuration and its rules.' },
  } },
  pt: { translation: {
    nav: { networks: 'Fontes', validators: 'Validadores', transformers: 'Transformadores', actions: 'Ações', runtime: 'Runtime', operation: 'Operação', harvesterAdmin: 'Coletor', logout: 'Sair' },
    common: { search: 'Buscar', state: 'Estado', all: 'Todos', save: 'Salvar', cancel: 'Cancelar', close: 'Fechar', confirm: 'Confirmar', delete: 'Excluir', parameters: 'Parâmetros', configuration: 'Configuração', actions: 'Ações', source: 'Fonte', action: 'Ação', worker: 'Worker', engine: 'Motor', loading: 'Carregando…', unavailable: 'Indisponível' },
    login: { title: 'Coletor', subtitle: 'Administração v5 da LA Referencia', description: 'Acesse a operação de fontes, ações e configurações da instalação.', username: 'Usuário', password: 'Senha', submit: 'Entrar', invalid: 'As credenciais são inválidas ou a API não está disponível.' },
    actions: { title: 'Ações da aplicação', activeEngine: 'Motor ativo: {{engine}}', noActions: 'sem ações detectadas', refresh: 'Atualizar catálogo', loadError: 'Não foi possível carregar o catálogo de ações.', refreshSuccess: 'Catálogo atualizado: {{created}} novas, {{updated}} atualizadas, {{unavailable}} indisponíveis.', key: 'Chave', workers: 'Workers', lastSeen: 'Última detecção', enabled: 'Habilitada', workerConfigs: 'Configurações de workers', workerDescription: 'Parâmetros globais dos workers. Aplicam-se às novas execuções de todas as fontes.', workerLoadError: 'Não foi possível carregar as configurações dos workers.', disableTitle: 'Desabilitar {{action}}', disableWarning: 'Novas execuções serão bloqueadas. Processos ativos ou na fila continuarão.', affected: '{{networks}} fontes e {{schedules}} agendamentos são afetados.', globalConfig: 'Configuração global de {{worker}}', noParams: 'Este componente não publica parâmetros configuráveis.', states: { ENABLED: 'Habilitada', DISABLED: 'Desabilitada', UNAVAILABLE: 'Indisponível', INVALID_CONFIGURATION: 'Configuração inválida' } },
    runtime: { title: 'Runtime', loadError: 'Não foi possível obter o estado do motor.', summary: 'Motor: {{engine}} · {{running}} processos em execução · {{queued}} na fila', status: 'Estado', cancellation: 'Cancelamento' },
    diagnostics: { title: 'Diagnóstico da fonte', noSnapshot: 'Esta fonte ainda não possui um snapshot válido com informações de diagnóstico.', back: 'Voltar às fontes', snapshot: 'Snapshot', filters: 'Os filtros afetam o resumo, as regras e os registros.', search: 'Buscar identificador', validity: 'Validade', transformation: 'Transformação', failedRule: 'Regra com falha', all: 'Todos', valid: 'Válidos', invalid: 'Inválidos', transformed: 'Transformados', reset: 'Redefinir filtros' },
    networks: { center: 'Centro de operações', title: 'Fontes coletadas', subtitle: 'Monitore resultados, agendamento e atividade em tempo real.', sources: 'Fontes', active: 'Ativas', search: 'Buscar por sigla, repositório ou instituição', loadError: 'Não foi possível carregar as fontes.', inventory: 'Inventário de fontes', results: '{{count}} resultado', results_plural: '{{count}} resultados', refresh: 'atualização automática a cada 10 segundos', acronym: 'Sigla', repository: 'Repositório', institution: 'Instituição', latestSnapshot: 'Último snapshot', noSnapshots: 'Sem snapshots', edit: 'Editar fonte', editDescription: 'As alterações são salvas atomicamente, incluindo as associações de processamento.', main: 'Principal', processing: 'Validação', profile: 'Dados específicos', actionSchedule: 'Ações e agendamento', saveChanges: 'Salvar alterações', principalData: 'Dados principais e origem da coleta', url: 'URL OAI-PMH', metadataPrefix: 'Metadata prefix', storageFormat: 'Formato de armazenamento', sets: 'Sets OAI-PMH', cron: 'Cron da coleta', validators: 'Validadores e transformadores', actionsOfSource: 'Ações desta fonte', acronymHelp: 'Não pode ser alterado para preservar a identidade da fonte.', published: 'Fonte publicada', allSets: 'Adicione um ou mais setSpec; deixe vazio para coletar todos.', noSchedule: 'Expressão cron de seis campos; deixe vazio para não agendar a fonte.', processingRelations: 'Estas quatro relações são atualizadas com o restante da fonte.', manual: 'Permitir execução manual', scheduled: 'Executar quando o agendamento da fonte disparar', actionModifiers: 'Modificadores próprios da ação', profileUnavailable: 'A fonte usa um perfil de atributos que não está publicado por esta instalação v5.', noPrevalidator: 'Sem pré-validador', noValidator: 'Sem validador', noTransformer: 'Sem transformador' },
    configuration: { reusable: 'Configurações reutilizáveis e suas regras.', create: 'Criar {{kind}}', validator: 'validador', transformer: 'transformador', name: 'Nome', description: 'Descrição', clone: 'Clonar', noItems: 'Não há configurações.', loadError: 'Não foi possível carregar a lista.', deleteTitle: 'Excluir {{name}}', deleteWarning: 'Esta ação excluirá a configuração e suas regras.' },
  } },
} as const

const saved = localStorage.getItem('lrharvester.locale')
void i18n.use(initReactI18next).init({ resources, lng: saved || navigator.language.split('-')[0], fallbackLng: 'es', interpolation: { escapeValue: false } })
i18n.on('languageChanged', language => localStorage.setItem('lrharvester.locale', language))
export default i18n
