export const networkFilterTranslations = {
  es: {
    title: 'Filtrar y ordenar', sort: 'Ordenar por', direction: 'Dirección', asc: 'Ascendente', desc: 'Descendente', more: 'Más filtros', less: 'Menos filtros', clear: 'Limpiar', failures: 'Con fallos', attention: 'Atención requerida', any: 'Cualquiera', harvest: 'Último snapshot', indexing: 'Indexación', valid: 'Cosecha válida disponible', indexer: 'Indexador', allIndexers: 'Resultado global', activeVisible: 'Activas en esta página', noResults: 'No hay fuentes que coincidan con estos filtros.', scope: 'Los estados e indexaciones corresponden al último snapshot. Las categorías se combinan con AND; los valores de cada categoría con OR. El indexador elegido afecta al filtro y al orden de indexación; la columna muestra el resumen global.', indexersError: 'No se pudo cargar la lista de indexadores.', tagsSortHelp: 'Se comparan todas las etiquetas en orden alfabético; sin etiquetas al final.', attentionHelp: 'Primero errores de cosecha sin válida disponible, luego errores con válida anterior, fallos de indexación, cosechas detenidas y fuentes sin válida.',
    sorts: { acronym: 'Acrónimo', tags: 'Etiquetas', latestSnapshot: 'Fecha del último snapshot', lastValidSnapshot: 'Fecha de la última válida', snapshotStatus: 'Estado del snapshot', indexStatus: 'Resultado de indexación', attention: 'Atención requerida', name: 'Repositorio', institutionName: 'Institución', id: 'ID', published: 'Publicación' },
    harvests: { valid: 'Validado', error: 'Error de cosecha', running: 'Cosechando o reintentando', stopped: 'Cosecha detenida', finished: 'Finalizado sin validar', none: 'Sin snapshots', INITIALIZED: 'Esperando', INDEXING: 'Indexando', INDEXING_FINISHED_ERROR: 'Error de indexación (legacy)', INDEXING_FINISHED_VALID: 'Indexación finalizada (legacy)', UNKNOWN: 'Desconocido', EMPTY_INCREMENTAL: 'Sin cambios' },
    indexes: { INDEXED: 'OK', FAILED: 'Fallo', UNKNOWN: 'Sin resultado' },
    validities: { latest: 'La última es válida', previous: 'Hay una válida anterior', none: 'Ninguna válida', any: 'Hay alguna válida' },
  },
  en: {
    title: 'Filter and sort', sort: 'Sort by', direction: 'Direction', asc: 'Ascending', desc: 'Descending', more: 'More filters', less: 'Fewer filters', clear: 'Clear', failures: 'With failures', attention: 'Needs attention', any: 'Any', harvest: 'Latest snapshot', indexing: 'Indexing', valid: 'Valid harvest available', indexer: 'Indexer', allIndexers: 'Overall result', activeVisible: 'Active on this page', noResults: 'No sources match these filters.', scope: 'States and indexing refer to the latest snapshot. Categories use AND; values within each category use OR. The selected indexer affects indexing filters and sorting; the table shows the overall result.', indexersError: 'Could not load the list of indexers.', tagsSortHelp: 'All tags are compared in alphabetical order; sources without tags come last.', attentionHelp: 'Harvest errors without a valid harvest first, then errors with a previous valid harvest, indexing failures, stopped harvests and sources without a valid harvest.',
    sorts: { acronym: 'Acronym', tags: 'Tags', latestSnapshot: 'Latest snapshot date', lastValidSnapshot: 'Last valid harvest date', snapshotStatus: 'Snapshot state', indexStatus: 'Indexing result', attention: 'Needs attention', name: 'Repository', institutionName: 'Institution', id: 'ID', published: 'Publication' },
    harvests: { valid: 'Validated', error: 'Harvest error', running: 'Harvesting or retrying', stopped: 'Harvest stopped', finished: 'Finished, not yet validated', none: 'No snapshots', INITIALIZED: 'Waiting', INDEXING: 'Indexing', INDEXING_FINISHED_ERROR: 'Indexing error (legacy)', INDEXING_FINISHED_VALID: 'Indexing finished (legacy)', UNKNOWN: 'Unknown', EMPTY_INCREMENTAL: 'No changes' },
    indexes: { INDEXED: 'OK', FAILED: 'Failed', UNKNOWN: 'No result' },
    validities: { latest: 'Latest is valid', previous: 'Previous valid harvest available', none: 'No valid harvest', any: 'Any valid harvest available' },
  },
  pt: {
    title: 'Filtrar e ordenar', sort: 'Ordenar por', direction: 'Direção', asc: 'Crescente', desc: 'Decrescente', more: 'Mais filtros', less: 'Menos filtros', clear: 'Limpar', failures: 'Com falhas', attention: 'Requer atenção', any: 'Qualquer', harvest: 'Último snapshot', indexing: 'Indexação', valid: 'Coleta válida disponível', indexer: 'Indexador', allIndexers: 'Resultado global', activeVisible: 'Ativas nesta página', noResults: 'Nenhuma fonte corresponde a estes filtros.', scope: 'Os estados e a indexação correspondem ao último snapshot. As categorias usam AND; os valores de cada categoria usam OR. O indexador escolhido afeta o filtro e a ordem de indexação; a coluna mostra o resultado global.', indexersError: 'Não foi possível carregar a lista de indexadores.', tagsSortHelp: 'Todas as etiquetas são comparadas em ordem alfabética; fontes sem etiquetas ficam por último.', attentionHelp: 'Primeiro erros de coleta sem uma válida, depois erros com válida anterior, falhas de indexação, coletas paradas e fontes sem coleta válida.',
    sorts: { acronym: 'Sigla', tags: 'Etiquetas', latestSnapshot: 'Data do último snapshot', lastValidSnapshot: 'Data da última válida', snapshotStatus: 'Estado do snapshot', indexStatus: 'Resultado da indexação', attention: 'Requer atenção', name: 'Repositório', institutionName: 'Instituição', id: 'ID', published: 'Publicação' },
    harvests: { valid: 'Validado', error: 'Erro de coleta', running: 'Coletando ou tentando novamente', stopped: 'Coleta parada', finished: 'Finalizado sem validação', none: 'Sem snapshots', INITIALIZED: 'Aguardando', INDEXING: 'Indexando', INDEXING_FINISHED_ERROR: 'Erro de indexação (legado)', INDEXING_FINISHED_VALID: 'Indexação finalizada (legado)', UNKNOWN: 'Desconhecido', EMPTY_INCREMENTAL: 'Sem alterações' },
    indexes: { INDEXED: 'OK', FAILED: 'Falha', UNKNOWN: 'Sem resultado' },
    validities: { latest: 'A última é válida', previous: 'Há uma válida anterior', none: 'Nenhuma válida', any: 'Há alguma válida' },
  },
} as const
