import RefreshIcon from '@mui/icons-material/Refresh'
import SettingsIcon from '@mui/icons-material/Settings'
import ArrowUpwardIcon from '@mui/icons-material/ArrowUpward'
import ArrowDownwardIcon from '@mui/icons-material/ArrowDownward'
import { Alert, Box, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, IconButton, MenuItem, Paper, Stack, Switch, Table, TableBody, TableCell, TableHead, TableRow, TextField, Tooltip, Typography } from '@mui/material'
import Form from '@rjsf/mui'
import validator from '@rjsf/validator-ajv8'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import type { ApiClient } from '../../api/client'
import type { ApiError } from '../../api/problem-detail'
import type { ApplicationAction, ApplicationActionState, ApplicationActionUsage, WorkerConfiguration } from '../../api/types'
import { queryKeys } from '../../api/query-keys'
import { useAuth } from '../../auth/AuthProvider'
import { useTranslation } from 'react-i18next'

const stateColor: Record<ApplicationActionState, 'success' | 'default' | 'warning' | 'error'> = { ENABLED: 'success', DISABLED: 'default', UNAVAILABLE: 'warning', INVALID_CONFIGURATION: 'error' }

export function ApplicationActionsPage({ client }: { client: ApiClient }) {
  const cache = useQueryClient(); const { user } = useAuth(); const canEdit = Boolean(user?.roles.includes('ADMIN'))
  const { t, i18n } = useTranslation()
  const query = useQuery({ queryKey: queryKeys.applicationActions, queryFn: () => client.applicationActions() })
  const workers = useQuery({ queryKey: queryKeys.workerConfigurations, queryFn: () => client.workerConfigurations() })
  const [search, setSearch] = useState(''); const [state, setState] = useState('ALL'); const [confirm, setConfirm] = useState<{ action: ApplicationAction; usage: ApplicationActionUsage } | null>(null); const [editing, setEditing] = useState<WorkerConfiguration | null>(null)
  const update = useMutation({ mutationFn: ({ action, enabled, configuration }: { action: ApplicationAction; enabled: boolean; configuration: Record<string, unknown> }) => client.updateApplicationAction(action.actionKey, enabled, configuration), onSuccess: () => { cache.invalidateQueries({ queryKey: queryKeys.applicationActions }); cache.invalidateQueries({ queryKey: queryKeys.capabilities }); setConfirm(null) } })
  const move = useMutation({ mutationFn: ({ action, direction }: { action: ApplicationAction; direction: 'UP' | 'DOWN' }) => client.moveApplicationAction(action.actionKey, direction), onSuccess: () => { cache.invalidateQueries({ queryKey: queryKeys.applicationActions }); cache.invalidateQueries({ queryKey: queryKeys.capabilities }) } })
  const updateWorker = useMutation({ mutationFn: ({ worker, configuration }: { worker: WorkerConfiguration; configuration: Record<string, unknown> }) => client.updateWorkerConfiguration(worker.workerKey, configuration), onSuccess: () => { cache.invalidateQueries({ queryKey: queryKeys.workerConfigurations }); setEditing(null) } })
  const refresh = useMutation({ mutationFn: () => client.refreshApplicationActions(), onSuccess: () => { cache.invalidateQueries({ queryKey: queryKeys.applicationActions }); cache.invalidateQueries({ queryKey: queryKeys.capabilities }) } })
  const stateLabel = (value: ApplicationActionState) => t(`actions.states.${value}`)
  const filtered = useMemo(() => (query.data || []).filter(action => (state === 'ALL' || action.state === state) && `${action.actionKey} ${action.definition.name || ''}`.toLowerCase().includes(search.toLowerCase())), [query.data, search, state])
  const toggle = async (action: ApplicationAction, enabled: boolean) => {
    if (!enabled) { setConfirm({ action, usage: await client.applicationActionUsage(action.actionKey) }); return }
    update.mutate({ action, enabled, configuration: action.configuration })
  }
  if (query.isLoading) return <CircularProgress />
  if (query.isError) return <Alert severity="error">{t('actions.loadError')}</Alert>
  return <Stack spacing={3}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" gap={2}><Box><Typography variant="h4">{t('actions.title')}</Typography><Typography color="text.secondary">{t('actions.activeEngine', { engine: query.data?.[0]?.engineType || t('actions.noActions') })}</Typography></Box>{canEdit && <Button startIcon={<RefreshIcon />} variant="outlined" disabled={refresh.isPending} onClick={() => refresh.mutate()}>{t('actions.refresh')}</Button>}</Stack>
    {(update.isError || move.isError || updateWorker.isError || refresh.isError) && <Alert severity="error">{((update.error || move.error || updateWorker.error || refresh.error) as ApiError).message}</Alert>}
    {refresh.data && <Alert severity="success">{t('actions.refreshSuccess', refresh.data)}</Alert>}
    <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField label={t('common.search')} value={search} onChange={event => setSearch(event.target.value)} fullWidth /><TextField select label={t('common.state')} value={state} onChange={event => setState(event.target.value)} sx={{ minWidth: 220 }}><MenuItem value="ALL">{t('common.all')}</MenuItem>{(['ENABLED', 'DISABLED', 'UNAVAILABLE', 'INVALID_CONFIGURATION'] as ApplicationActionState[]).map(key => <MenuItem key={key} value={key}>{stateLabel(key)}</MenuItem>)}</TextField></Stack>
    <Paper variant="outlined"><Table><TableHead><TableRow><TableCell width={110}>Orden</TableCell><TableCell>{t('common.action')}</TableCell><TableCell>{t('actions.key')}</TableCell><TableCell>{t('actions.workers')}</TableCell><TableCell>{t('common.state')}</TableCell><TableCell>{t('actions.lastSeen')}</TableCell><TableCell align="right">{t('actions.enabled')}</TableCell></TableRow></TableHead><TableBody>{filtered.map(action => { const position = (query.data || []).findIndex(item => item.actionKey === action.actionKey); const displayOrder = action.order ?? position; return <TableRow key={action.actionKey}><TableCell><Stack direction="row" alignItems="center" spacing={.25}><Typography variant="body2" fontWeight={700}>{displayOrder >= 0 ? displayOrder + 1 : '—'}</Typography><Tooltip title="Subir"><span><IconButton size="small" disabled={!canEdit || move.isPending || position <= 0} onClick={() => move.mutate({ action, direction: 'UP' })}><ArrowUpwardIcon fontSize="inherit" /></IconButton></span></Tooltip><Tooltip title="Bajar"><span><IconButton size="small" disabled={!canEdit || move.isPending || position < 0 || position === (query.data || []).length - 1} onClick={() => move.mutate({ action, direction: 'DOWN' })}><ArrowDownwardIcon fontSize="inherit" /></IconButton></span></Tooltip></Stack></TableCell><TableCell><Typography fontWeight={600}>{action.definition.name || action.actionKey}</Typography><Typography variant="body2" color="text.secondary">{action.definition.description}</Typography></TableCell><TableCell><code>{action.actionKey}</code></TableCell><TableCell>{(action.definition.workers || []).map(worker => <Typography key={worker} variant="body2"><code>{worker}</code></Typography>)}</TableCell><TableCell><Chip size="small" label={stateLabel(action.state)} color={stateColor[action.state]} /></TableCell><TableCell>{formatDate(action.lastSeenAt, i18n.language)}</TableCell><TableCell align="right"><FormControlLabel label="" control={<Switch checked={action.enabled} disabled={!canEdit || !action.available || update.isPending} onChange={event => void toggle(action, event.target.checked)} />} /></TableCell></TableRow> })}</TableBody></Table></Paper>
    <Box><Typography variant="h5" gutterBottom>{t('actions.workerConfigs')}</Typography><Typography color="text.secondary" sx={{ mb: 1 }}>{t('actions.workerDescription')}</Typography><Paper variant="outlined"><Table><TableHead><TableRow><TableCell>{t('common.worker')}</TableCell><TableCell>{t('actions.bean')}</TableCell><TableCell>{t('actions.lastSeen')}</TableCell><TableCell align="right">{t('common.configuration')}</TableCell></TableRow></TableHead><TableBody>{(workers.data || []).map(worker => <TableRow key={worker.workerKey}><TableCell><Typography fontWeight={600}>{t(`actions.workerNames.${worker.workerKey}`, { defaultValue: worker.workerKey })}</Typography>{!worker.available && <Chip size="small" label={t('common.unavailable')} color="warning" />}</TableCell><TableCell><code>{worker.definition.beanName || '—'}</code></TableCell><TableCell>{formatDate(worker.lastSeenAt, i18n.language)}</TableCell><TableCell align="right"><Button size="small" startIcon={<SettingsIcon />} disabled={!worker.available} onClick={() => setEditing(worker)}>{t('common.parameters')}</Button></TableCell></TableRow>)}</TableBody></Table></Paper>{workers.isError && <Alert severity="error" sx={{ mt: 1 }}>{t('actions.workerLoadError')}</Alert>}</Box>
    <Dialog open={Boolean(confirm)} onClose={() => setConfirm(null)} maxWidth="sm" fullWidth><DialogTitle>Deshabilitar {confirm?.action.actionKey}</DialogTitle><DialogContent><Alert severity="warning" sx={{ mb: 2 }}>Se bloquearán las ejecuciones nuevas. Los procesos activos o en cola continuarán.</Alert><Typography>{confirm?.usage.networkCount || 0} fuentes y {confirm?.usage.scheduleCount || 0} schedules están afectados.</Typography>{confirm?.usage.networks.map(network => <Typography key={network.id} variant="body2">• {network.acronym}: {network.relations.join(', ')}</Typography>)}</DialogContent><DialogActions><Button onClick={() => setConfirm(null)}>Cancelar</Button><Button color="error" variant="contained" onClick={() => confirm && update.mutate({ action: confirm.action, enabled: false, configuration: confirm.action.configuration })}>Deshabilitar</Button></DialogActions></Dialog>
    {editing && <WorkerConfigurationDialog worker={editing} canEdit={canEdit} saving={updateWorker.isPending} onClose={() => setEditing(null)} onSave={configuration => updateWorker.mutate({ worker: editing, configuration })} />}
  </Stack>
}

function WorkerConfigurationDialog({ worker, canEdit, saving, onClose, onSave }: { worker: WorkerConfiguration; canEdit: boolean; saving: boolean; onClose: () => void; onSave: (value: Record<string, unknown>) => void }) {
  const { t } = useTranslation()
  const [configuration, setConfiguration] = useState(worker.configuration); const hasSchema = Boolean(worker.schema.properties && Object.keys(worker.schema.properties as object).length)
  const schema = { ...worker.schema, properties: Object.fromEntries(Object.entries(worker.schema.properties || {}).map(([name, property]) => [name, { ...property, title: t(`actions.workerProperties.${worker.workerKey}.${name}`, { defaultValue: property.title || name }) }])) }
  return <Dialog open onClose={onClose} maxWidth="md" fullWidth><DialogTitle>{t('actions.globalConfig', { worker: t(`actions.workerNames.${worker.workerKey}`, { defaultValue: worker.workerKey }) })}</DialogTitle><DialogContent>{hasSchema ? <Form schema={schema} validator={validator} formData={configuration} liveValidate showErrorList={false} readonly={!canEdit} onChange={event => setConfiguration((event.formData || {}) as Record<string, unknown>)}><span /></Form> : <Alert severity="info">{t('actions.noParams')}</Alert>}</DialogContent><DialogActions><Button onClick={onClose}>{t('common.close')}</Button>{canEdit && <Button variant="contained" disabled={saving} onClick={() => onSave(hasSchema ? configuration : {})}>{t('common.save')}</Button>}</DialogActions></Dialog>
}

function formatDate(value: string | null, locale: string) { return value ? new Intl.DateTimeFormat(locale, { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—' }
