export const runtimeExplanations = {
  es: {
    queues: {
      title: 'Ejecución y espera', active: 'Plazas de ejecución ocupadas', pending: 'Tareas en espera',
      subtitle: 'Estado de las tareas admitidas · actualización cada 10 segundos',
      overview: 'Una acción puede tener varios pasos de trabajo. Estos límites cuentan tareas (workers), no registros cosechados ni acciones completas. Todas las fuentes comparten la capacidad global.',
      activeHelp: 'Una plaza permanece ocupada mientras la tarea está reservada, en ejecución o terminando tras una cancelación.',
      pendingHelp: 'La espera incluye los siguientes pasos de cada fuente y las tareas que aguardan capacidad o un recurso compartido. Las solicitudes rechazadas no entran en esta cola.',
      schedulingHelp: 'Cada fuente ejecuta una tarea a la vez y conserva el orden de sus pasos. Puede haber plazas libres aunque otras tareas esperen por su fuente o por un recurso compartido.',
      contexts: 'Trabajo por fuente', contextHelp: 'Abre una fila para consultar los siguientes pasos y horarios.',
      searchSource: 'Buscar fuente', sourceFilter: 'Actividad de la fuente',
      sourceFilters: { all: 'Todas', active: 'Con plaza ocupada', waiting: 'Con tareas en espera' },
      sourceFilterHelp: 'Una fuente puede ocupar una plaza y tener tareas en espera a la vez. Los filtros afectan solo a esta tabla; los indicadores superiores siguen mostrando el total de la instalación.',
      tableScrollHelp: 'Desliza la tabla horizontalmente para ver todas las columnas.',
      sourceCount: '{{shown}} de {{total}} fuentes', pendingSteps: 'Pendientes', waitReason: 'Motivo de espera',
      noMatchingSources: 'No hay fuentes que coincidan con la búsqueda y el filtro.',
      details: 'Detalle', showSourceDetails: 'Mostrar detalle de {{source}}', hideSourceDetails: 'Ocultar detalle de {{source}}', sourceDetails: 'Detalle de {{source}}',
      resourceOwner: 'Recurso ocupado por {{source}}',
      shortReasons: { CONTEXT_ORDER: 'Orden de la fuente', CONTEXT_BUSY: 'Orden de la fuente', LANE_BUSY: 'Recurso compartido', GLOBAL_CAPACITY: 'Capacidad global', EXECUTOR_UNAVAILABLE: 'Inicio pendiente' },
      admittedAt: 'Admitida: {{time}}', startedAt: 'Inicio: {{time}}',
      sourcesPerPage: 'Fuentes por página', pageRange: '{{from}}–{{to}} de {{total}}',
      pagination: { first: 'Primera página', last: 'Última página', next: 'Página siguiente', previous: 'Página anterior' },
      now: 'Tarea actual', next: 'Próximos pasos', noActive: 'Sin tarea en ejecución', noPending: 'Sin pasos pendientes',
      waitingSince: 'En espera desde {{time}}', reasonsTitle: 'Motivos de espera', sourceWait: 'Orden de la fuente', resourceWait: 'Recurso compartido', capacityWait: 'Capacidad global',
      laneDetails: 'Detalle técnico de recursos compartidos (lanes)',
      laneHelp: 'Una lane agrupa tareas que deben usar un recurso de una en una, incluso entre fuentes distintas. No añade plazas de ejecución. Solo se muestran lanes con trabajo activo o pendiente.',
      laneBlocked: 'Esperan por este recurso', laneScheduled: 'Pasos asociados en espera',
      blockedBy: 'El recurso está ocupado por {{worker}} de {{source}}. Esta tarea podrá avanzar cuando se libere y haya una plaza global.',
      reasons: { CONTEXT_ORDER: 'Este paso espera a los pasos anteriores de la misma fuente.', CONTEXT_BUSY: 'La tarea actual de esta fuente debe terminar antes de iniciar el siguiente paso.', LANE_BUSY: 'Otra tarea está usando el mismo recurso compartido.', GLOBAL_CAPACITY: 'Espera una plaza de ejecución global disponible.', EXECUTOR_UNAVAILABLE: 'La plaza está reservada, pero el inicio de la tarea está pendiente de reintento.' },
      workerNames: {
        harvestingWorker: 'Cosecha de metadatos', validationWorker: 'Validación y transformación', frontendIndexerWorker: 'Indexación del buscador', xoaiIndexerWorker: 'Indexación OAI-PMH', darkStageWorker: 'Enviar a dARK', darkReconcileWorker: 'Reconciliar desde dARK', networkCleanWorker: 'Limpieza de la fuente', networkDeleteWorker: 'Eliminación de la fuente',
        frontendDeleteWorker: 'Eliminación del índice del buscador', xoaiDeleteWorker: 'Eliminación del índice OAI-PMH', semanticIndexerWorker: 'Indexación semántica', semanticDeleteWorker: 'Eliminación del índice semántico', metadataOrphanCleanupWorker: 'Limpieza de metadatos huérfanos',
        HarvestingWorker: 'Cosecha de metadatos', ValidationWorker: 'Validación y transformación', IndexerWorker: 'Indexación', SemanticIndexerWorker: 'Indexación semántica', FullUnindexerWorker: 'Eliminación de registros del índice', DarkStageWorker: 'Enviar a dARK', DarkReconcileWorker: 'Reconciliar desde dARK', NetworkCleanWorker: 'Mantenimiento de la fuente', MetadataOrphanCleanupWorker: 'Limpieza de metadatos huérfanos',
      },
    },
    configuration: {
      title: 'Límites y comportamiento', executionTitle: 'Ejecución y admisión de tareas',
      executionHelp: 'Se aplican a toda la instalación. Aumentar la concurrencia permite más trabajo en paralelo, pero también puede aumentar el consumo de CPU, memoria y conexiones.',
      advancedTitle: 'Historial reciente y apagado', advancedHelp: 'Estos ajustes controlan cuánto tiempo se conservan los resultados temporales del runtime y cómo se detiene el servicio.',
      fields: { concurrentTasks: 'Tareas simultáneas', maxQueuedTasks: 'Máximo de tareas en espera', resultRetentionSeconds: 'Duración del historial reciente (segundos)', maxRetainedResults: 'Máximo de resultados recientes', shutdownTimeoutSeconds: 'Espera de apagado (segundos)' },
      fieldHelp: {
        concurrentTasks: 'Máximo de plazas ocupadas. Subirlo permite iniciar más tareas si su fuente y su recurso están libres. Bajarlo deja terminar las tareas actuales antes de admitir nuevas plazas.',
        maxQueuedTasks: 'Máximo de tareas admitidas que deben esperar, incluidos los siguientes pasos de una acción. Si una solicitud supera ese espacio, se rechaza completa. Con 0, solo se acepta trabajo que pueda empezar inmediatamente; una acción con varios pasos puede rechazarse incluso con una plaza libre.',
        resultRetentionSeconds: 'Los resultados de tareas terminadas se retiran del runtime al superar esta edad. Es un historial temporal en memoria; no elimina snapshots, metadatos ni sus logs y no se conserva al reiniciar.',
        maxRetainedResults: 'Tope de resultados de tareas terminadas. Si se supera, se retiran los más antiguos aunque no haya vencido su duración. Actúa junto con el límite de tiempo.',
        shutdownTimeoutSeconds: 'Al apagar, se cancelan las tareas en espera y se solicita detener e interrumpir las activas. Este plazo permite que terminen su cierre; al agotarse se vuelve a intentar interrumpir las que sigan activas. Con 0 no hay espera adicional.',
      },
      preview: 'Al aplicar: hasta {{active}} tareas simultáneas y {{queued}} tareas en espera. Siguen vigentes el orden por fuente y la exclusión de recursos compartidos.',
      reduced: 'Estás reduciendo un límite. Las tareas ya admitidas se conservan; el nuevo valor limita las siguientes admisiones o inicios. Temporalmente puede verse una ocupación superior al límite.',
      current: 'Valor aplicado: {{value}}', integerRange: 'Introduce un entero entre {{min}} y {{max}}.',
    },
  },
  en: {
    queues: {
      title: 'Execution and waiting', active: 'Occupied execution slots', pending: 'Waiting tasks',
      subtitle: 'Admitted task status · updates every 10 seconds',
      overview: 'An action can contain several work steps. These limits count tasks (workers), not harvested records or complete actions. All sources share global capacity.',
      activeHelp: 'A slot stays occupied while a task is reserved, running or finishing after a cancellation request.',
      pendingHelp: 'Waiting includes subsequent steps for each source and tasks awaiting capacity or a shared resource. Rejected requests do not enter this queue.',
      schedulingHelp: 'Each source runs one task at a time and preserves step order. Slots can remain free while tasks wait for their source or a shared resource.',
      contexts: 'Work by source', contextHelp: 'Expand a row to see the next steps and timestamps.',
      searchSource: 'Search sources', sourceFilter: 'Source activity',
      sourceFilters: { all: 'All', active: 'Occupying a slot', waiting: 'With waiting tasks' },
      sourceFilterHelp: 'A source can occupy a slot and have waiting tasks at the same time. Filters affect only this table; the indicators above still show installation totals.',
      tableScrollHelp: 'Scroll the table horizontally to see all columns.',
      sourceCount: '{{shown}} of {{total}} sources', pendingSteps: 'Pending', waitReason: 'Reason for waiting',
      noMatchingSources: 'No sources match the search and filter.',
      details: 'Details', showSourceDetails: 'Show details for {{source}}', hideSourceDetails: 'Hide details for {{source}}', sourceDetails: 'Details for {{source}}',
      resourceOwner: 'Resource occupied by {{source}}',
      shortReasons: { CONTEXT_ORDER: 'Source order', CONTEXT_BUSY: 'Source order', LANE_BUSY: 'Shared resource', GLOBAL_CAPACITY: 'Global capacity', EXECUTOR_UNAVAILABLE: 'Start pending' },
      admittedAt: 'Admitted: {{time}}', startedAt: 'Started: {{time}}',
      sourcesPerPage: 'Sources per page', pageRange: '{{from}}–{{to}} of {{total}}',
      pagination: { first: 'First page', last: 'Last page', next: 'Next page', previous: 'Previous page' },
      now: 'Current task', next: 'Next steps', noActive: 'No task running', noPending: 'No pending steps',
      waitingSince: 'Waiting since {{time}}', reasonsTitle: 'Reasons for waiting', sourceWait: 'Source order', resourceWait: 'Shared resource', capacityWait: 'Global capacity',
      laneDetails: 'Shared resource technical details (lanes)',
      laneHelp: 'A lane groups tasks that must use a resource one at a time, even across sources. It does not add execution slots. Only lanes with active or pending work are shown.',
      laneBlocked: 'Waiting for this resource', laneScheduled: 'Associated waiting steps',
      blockedBy: 'The resource is occupied by {{worker}} for {{source}}. This task can proceed when it is released and a global slot is available.',
      reasons: { CONTEXT_ORDER: 'This step waits for earlier steps from the same source.', CONTEXT_BUSY: 'The current task for this source must finish before the next step starts.', LANE_BUSY: 'Another task is using the same shared resource.', GLOBAL_CAPACITY: 'Waiting for an available global execution slot.', EXECUTOR_UNAVAILABLE: 'The slot is reserved, but starting the task is awaiting retry.' },
      workerNames: {
        harvestingWorker: 'Metadata harvesting', validationWorker: 'Validation and transformation', frontendIndexerWorker: 'Search indexing', xoaiIndexerWorker: 'OAI-PMH indexing', darkStageWorker: 'Send to dARK', darkReconcileWorker: 'Reconcile from dARK', networkCleanWorker: 'Source cleanup', networkDeleteWorker: 'Source deletion',
        frontendDeleteWorker: 'Search index deletion', xoaiDeleteWorker: 'OAI-PMH index deletion', semanticIndexerWorker: 'Semantic indexing', semanticDeleteWorker: 'Semantic index deletion', metadataOrphanCleanupWorker: 'Orphan metadata cleanup',
        HarvestingWorker: 'Metadata harvesting', ValidationWorker: 'Validation and transformation', IndexerWorker: 'Indexing', SemanticIndexerWorker: 'Semantic indexing', FullUnindexerWorker: 'Index record deletion', DarkStageWorker: 'Send to dARK', DarkReconcileWorker: 'Reconcile from dARK', NetworkCleanWorker: 'Source maintenance', MetadataOrphanCleanupWorker: 'Orphan metadata cleanup',
      },
    },
    configuration: {
      title: 'Limits and behavior', executionTitle: 'Task execution and admission',
      executionHelp: 'These limits apply across the installation. Increasing concurrency allows more parallel work but can also increase CPU, memory and connection use.',
      advancedTitle: 'Recent history and shutdown', advancedHelp: 'These settings control how long temporary runtime results are retained and how the service stops.',
      fields: { concurrentTasks: 'Concurrent tasks', maxQueuedTasks: 'Maximum waiting tasks', resultRetentionSeconds: 'Recent history duration (seconds)', maxRetainedResults: 'Maximum recent results', shutdownTimeoutSeconds: 'Shutdown wait (seconds)' },
      fieldHelp: {
        concurrentTasks: 'Maximum occupied slots. Increasing this allows more tasks to start if their source and resource are free. Lowering it lets current tasks finish before reserving new slots.',
        maxQueuedTasks: 'Maximum admitted tasks that must wait, including later steps of an action. A request that exceeds this space is rejected as a whole. With 0, only work that can start immediately is accepted; an action with several steps can be rejected even with a free slot.',
        resultRetentionSeconds: 'Completed task results leave runtime when older than this duration. This is temporary in-memory history; it does not delete snapshots, metadata or their logs and does not survive restarts.',
        maxRetainedResults: 'Cap on completed task results. The oldest results are removed when exceeded, even if their duration has not expired. This works together with the time limit.',
        shutdownTimeoutSeconds: 'On shutdown, waiting tasks are cancelled and active tasks are asked to stop and interrupted. This time allows them to finish closing; when it expires, remaining tasks are interrupted again. With 0 there is no additional wait.',
      },
      preview: 'When applied: up to {{active}} concurrent tasks and {{queued}} waiting tasks. Source order and shared resource exclusion still apply.',
      reduced: 'You are lowering a limit. Already admitted work is preserved; the new value limits later admissions or starts. Occupancy can temporarily exceed the limit.',
      current: 'Applied value: {{value}}', integerRange: 'Enter an integer between {{min}} and {{max}}.',
    },
  },
  pt: {
    queues: {
      title: 'Execução e espera', active: 'Vagas de execução ocupadas', pending: 'Tarefas em espera',
      subtitle: 'Estado das tarefas admitidas · atualização a cada 10 segundos',
      overview: 'Uma ação pode conter várias etapas de trabalho. Estes limites contam tarefas (workers), não registros coletados nem ações completas. Todas as fontes compartilham a capacidade global.',
      activeHelp: 'Uma vaga permanece ocupada enquanto a tarefa está reservada, em execução ou terminando após uma solicitação de cancelamento.',
      pendingHelp: 'A espera inclui as próximas etapas de cada fonte e tarefas que aguardam capacidade ou um recurso compartilhado. Solicitações rejeitadas não entram nesta fila.',
      schedulingHelp: 'Cada fonte executa uma tarefa por vez e preserva a ordem das etapas. Pode haver vagas livres enquanto tarefas aguardam a fonte ou um recurso compartilhado.',
      contexts: 'Trabalho por fonte', contextHelp: 'Abra uma linha para consultar as próximas etapas e horários.',
      searchSource: 'Buscar fonte', sourceFilter: 'Atividade da fonte',
      sourceFilters: { all: 'Todas', active: 'Com vaga ocupada', waiting: 'Com tarefas em espera' },
      sourceFilterHelp: 'Uma fonte pode ocupar uma vaga e ter tarefas em espera ao mesmo tempo. Os filtros afetam apenas esta tabela; os indicadores acima continuam mostrando o total da instalação.',
      tableScrollHelp: 'Deslize a tabela horizontalmente para ver todas as colunas.',
      sourceCount: '{{shown}} de {{total}} fontes', pendingSteps: 'Pendentes', waitReason: 'Motivo de espera',
      noMatchingSources: 'Nenhuma fonte corresponde à busca e ao filtro.',
      details: 'Detalhes', showSourceDetails: 'Mostrar detalhes de {{source}}', hideSourceDetails: 'Ocultar detalhes de {{source}}', sourceDetails: 'Detalhes de {{source}}',
      resourceOwner: 'Recurso ocupado por {{source}}',
      shortReasons: { CONTEXT_ORDER: 'Ordem da fonte', CONTEXT_BUSY: 'Ordem da fonte', LANE_BUSY: 'Recurso compartilhado', GLOBAL_CAPACITY: 'Capacidade global', EXECUTOR_UNAVAILABLE: 'Início pendente' },
      admittedAt: 'Admitida: {{time}}', startedAt: 'Início: {{time}}',
      sourcesPerPage: 'Fontes por página', pageRange: '{{from}}–{{to}} de {{total}}',
      pagination: { first: 'Primeira página', last: 'Última página', next: 'Próxima página', previous: 'Página anterior' },
      now: 'Tarefa atual', next: 'Próximas etapas', noActive: 'Nenhuma tarefa em execução', noPending: 'Nenhuma etapa pendente',
      waitingSince: 'Aguardando desde {{time}}', reasonsTitle: 'Motivos de espera', sourceWait: 'Ordem da fonte', resourceWait: 'Recurso compartilhado', capacityWait: 'Capacidade global',
      laneDetails: 'Detalhes técnicos de recursos compartilhados (lanes)',
      laneHelp: 'Uma lane agrupa tarefas que devem usar um recurso uma por vez, inclusive entre fontes. Não adiciona vagas de execução. Apenas lanes com trabalho ativo ou pendente são exibidas.',
      laneBlocked: 'Aguardam este recurso', laneScheduled: 'Etapas associadas em espera',
      blockedBy: 'O recurso está ocupado por {{worker}} da fonte {{source}}. Esta tarefa poderá avançar quando o recurso for liberado e houver uma vaga global.',
      reasons: { CONTEXT_ORDER: 'Esta etapa aguarda as etapas anteriores da mesma fonte.', CONTEXT_BUSY: 'A tarefa atual desta fonte deve terminar antes de iniciar a próxima etapa.', LANE_BUSY: 'Outra tarefa está usando o mesmo recurso compartilhado.', GLOBAL_CAPACITY: 'Aguardando uma vaga de execução global disponível.', EXECUTOR_UNAVAILABLE: 'A vaga está reservada, mas o início da tarefa aguarda nova tentativa.' },
      workerNames: {
        harvestingWorker: 'Coleta de metadados', validationWorker: 'Validação e transformação', frontendIndexerWorker: 'Indexação da busca', xoaiIndexerWorker: 'Indexação OAI-PMH', darkStageWorker: 'Enviar para dARK', darkReconcileWorker: 'Reconciliar a partir do dARK', networkCleanWorker: 'Limpeza da fonte', networkDeleteWorker: 'Exclusão da fonte',
        frontendDeleteWorker: 'Exclusão do índice de busca', xoaiDeleteWorker: 'Exclusão do índice OAI-PMH', semanticIndexerWorker: 'Indexação semântica', semanticDeleteWorker: 'Exclusão do índice semântico', metadataOrphanCleanupWorker: 'Limpeza de metadados órfãos',
        HarvestingWorker: 'Coleta de metadados', ValidationWorker: 'Validação e transformação', IndexerWorker: 'Indexação', SemanticIndexerWorker: 'Indexação semântica', FullUnindexerWorker: 'Exclusão de registros do índice', DarkStageWorker: 'Enviar para dARK', DarkReconcileWorker: 'Reconciliar a partir do dARK', NetworkCleanWorker: 'Manutenção da fonte', MetadataOrphanCleanupWorker: 'Limpeza de metadados órfãos',
      },
    },
    configuration: {
      title: 'Limites e comportamento', executionTitle: 'Execução e admissão de tarefas',
      executionHelp: 'Os limites se aplicam a toda a instalação. Aumentar a concorrência permite mais trabalho em paralelo, mas também pode aumentar o consumo de CPU, memória e conexões.',
      advancedTitle: 'Histórico recente e desligamento', advancedHelp: 'Estes ajustes controlam por quanto tempo os resultados temporários do runtime são mantidos e como o serviço é encerrado.',
      fields: { concurrentTasks: 'Tarefas simultâneas', maxQueuedTasks: 'Máximo de tarefas em espera', resultRetentionSeconds: 'Duração do histórico recente (segundos)', maxRetainedResults: 'Máximo de resultados recentes', shutdownTimeoutSeconds: 'Espera de desligamento (segundos)' },
      fieldHelp: {
        concurrentTasks: 'Máximo de vagas ocupadas. Aumentar permite iniciar mais tarefas se a fonte e o recurso estiverem livres. Reduzir permite terminar as tarefas atuais antes de reservar novas vagas.',
        maxQueuedTasks: 'Máximo de tarefas admitidas que precisam esperar, incluindo as próximas etapas de uma ação. Se uma solicitação ultrapassar esse espaço, será rejeitada inteira. Com 0, só se aceita trabalho que possa começar imediatamente; uma ação com várias etapas pode ser rejeitada mesmo com uma vaga livre.',
        resultRetentionSeconds: 'Os resultados de tarefas concluídas saem do runtime ao superar esta duração. É um histórico temporário em memória; não exclui snapshots, metadados ou seus logs e não é mantido ao reiniciar.',
        maxRetainedResults: 'Limite de resultados de tarefas concluídas. Ao superar, os mais antigos são removidos mesmo que a duração não tenha vencido. Atua junto com o limite de tempo.',
        shutdownTimeoutSeconds: 'Ao desligar, as tarefas em espera são canceladas e solicita-se a parada e interrupção das ativas. Este prazo permite que concluam o encerramento; ao esgotar, tenta-se interromper novamente as que continuam ativas. Com 0 não há espera adicional.',
      },
      preview: 'Ao aplicar: até {{active}} tarefas simultâneas e {{queued}} tarefas em espera. A ordem por fonte e a exclusão de recursos compartilhados continuam válidas.',
      reduced: 'Você está reduzindo um limite. As tarefas já admitidas são mantidas; o novo valor limita as próximas admissões ou inícios. A ocupação pode superar temporariamente o limite.',
      current: 'Valor aplicado: {{value}}', integerRange: 'Informe um inteiro entre {{min}} e {{max}}.',
    },
  },
} as const
