export const queryKeys = {
  me: ['me'] as const,
  networkSummaries: (query: string) => ['network-summaries', query] as const,
  network: (id: number) => ['network', id] as const,
  networkRuntime: (id: number) => ['network-runtime', id] as const,
  validators: ['validators'] as const,
  validator: (id: number) => ['validator', id] as const,
  transformers: ['transformers'] as const,
  transformer: (id: number) => ['transformer', id] as const,
  ruleTypes: (kind: 'validator' | 'transformer', locale = 'es') => ['rule-types', kind, locale] as const,
  attributeProfiles: ['attribute-profiles'] as const,
  capabilities: ['capabilities'] as const,
  applicationActions: ['application-actions'] as const,
  workerConfigurations: ['worker-configurations'] as const,
  networkActions: (id: number) => ['networks', id, 'actions'] as const,
  networkSnapshots: (id: number) => ['networks', id, 'snapshots'] as const,
  diagnosticSummary: (snapshotId: number, filters: string) => ['snapshots', snapshotId, 'diagnostics', 'summary', filters] as const,
  diagnosticRecords: (snapshotId: number, filters: string) => ['snapshots', snapshotId, 'diagnostics', 'records', filters] as const,
  diagnosticOccurrences: (snapshotId: number, ruleId: number, filters: string) => ['snapshots', snapshotId, 'diagnostics', 'occurrences', ruleId, filters] as const,
  snapshotLogs: (snapshotId: number) => ['snapshots', snapshotId, 'logs'] as const,
  runtime: ['runtime'] as const,
}
