import { useState } from 'react'
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Select, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type { ApiClient } from '../../api/client'
import { useTranslation } from 'react-i18next'

export function UsersPage({ client }: { client: ApiClient }) {
  const { t } = useTranslation(); const qc = useQueryClient(); const users = useQuery({ queryKey: ['users'], queryFn: () => client.users() });
  const [open, setOpen] = useState(false); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState('ROLE_VIEWER'); const [error, setError] = useState('');
  const create = useMutation({ mutationFn: () => client.createUser({ username, password, roles: [role] }), onSuccess: () => { void qc.invalidateQueries({ queryKey: ['users'] }); setOpen(false); setUsername(''); setPassword(''); setError('') }, onError: e => setError(e instanceof Error ? e.message : 'Error') });
  const remove = useMutation({ mutationFn: (name: string) => client.deleteUser(name), onSuccess: () => void qc.invalidateQueries({ queryKey: ['users'] }), onError: e => setError(e instanceof Error ? e.message : 'Error') });
  const label = (key: string, fallback: string) => t(key, { defaultValue: fallback });
  return <Stack spacing={3}><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="h4">{label('users.title', 'Usuarios')}</Typography><Button variant="contained" onClick={() => setOpen(true)}>{label('users.new', 'Nuevo usuario')}</Button></Stack>{error && <Alert severity="error">{error}</Alert>}<Paper variant="outlined"><Table><TableHead><TableRow><TableCell>{label('users.username', 'Usuario')}</TableCell><TableCell>{label('users.roles', 'Roles')}</TableCell><TableCell align="right">{label('users.actions', 'Acciones')}</TableCell></TableRow></TableHead><TableBody>{users.data?.map(user => <TableRow key={user.username}><TableCell>{user.username}</TableCell><TableCell>{user.roles.join(' · ')}</TableCell><TableCell align="right"><Button color="error" onClick={() => { if (window.confirm(label('users.confirmDelete', '¿Eliminar este usuario?'))) remove.mutate(user.username) }}>{t('common.delete')}</Button></TableCell></TableRow>)}</TableBody></Table></Paper><Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{label('users.new', 'Nuevo usuario')}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label={label('users.username', 'Usuario')} value={username} onChange={e => setUsername(e.target.value)} /><TextField required inputProps={{ minLength: 8, maxLength: 200 }} helperText={label('users.passwordHelp', 'Debe tener entre 8 y 200 caracteres.')} label={label('users.password', 'Contraseña')} type="password" value={password} onChange={e => setPassword(e.target.value)} /><Select value={role} onChange={e => setRole(e.target.value)}><MenuItem value="ROLE_ADMIN">{label('users.admin', 'Administrador')}</MenuItem><MenuItem value="ROLE_VIEWER">{label('users.viewer', 'Solo lectura')}</MenuItem></Select></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>{t('common.cancel')}</Button><Button variant="contained" onClick={() => create.mutate()} disabled={create.isPending || password.length < 8 || username.trim().length === 0}>{t('common.save')}</Button></DialogActions></Dialog></Stack>
}
