import i18n from '../../i18n'

const resources = {
  es: { editor: {
    loading: 'Cargando configuración…', loadError: 'No se pudo cargar la configuración.', backValidators: 'Validadores', backTransformers: 'Transformadores', create: 'Crear {{kind}}', edit: 'Editar {{kind}}', configurationData: 'Datos de la configuración', metadataHint: 'Se guardan independientemente de las reglas.', rules: 'Reglas', ruleCount: '{{count}} regla', ruleCount_plural: '{{count}} reglas', editOneRule: 'edita una regla por vez.', addRule: 'Añadir regla', name: 'Nombre', description: 'Descripción', type: 'Tipo', mandatory: 'Obligatoria', quantifier: 'Cuantificador', order: 'Orden', actions: 'Acciones', unnamed: 'Sin nombre', incomplete: 'Configuración incompleta', unavailableType: 'Tipo no disponible', yes: 'Sí', no: 'No', moveUp: 'Subir', moveDown: 'Bajar', editRule: 'Editar regla', deleteRule: 'Eliminar regla', noRules: 'Aún no hay reglas. Añade la primera regla para configurarla.', cancel: 'Cancelar', saveConfiguration: 'Guardar configuración', close: 'Cerrar', newRule: 'Nueva regla', individualRule: 'Configuración individual de la regla {{number}}', remove: 'Quitar', specificConfiguration: 'Configuración específica: {{name}}', typeUnavailable: 'El tipo de esta regla no está disponible en el motor actual. Selecciona uno de los tipos publicados para continuar.', saveRule: 'Guardar esta regla', saveFirst: 'Guarda primero el {{kind}} para poder guardar reglas individualmente.', deleteTitle: '¿Eliminar esta regla?', deleteWarning: 'La regla dejará de formar parte de este {{kind}}. Esta acción no se puede deshacer.', savedConfiguration: 'El {{kind}} se guardó correctamente.', savedRule: 'La regla “{{name}}” se guardó correctamente.', deletedRule: 'La regla se eliminó correctamente.', reorderedRules: 'El orden de las reglas se actualizó correctamente.', incompleteRule: 'Selecciona un tipo y escribe un nombre.', quantifiers: { ZERO_ONLY: 'Exactamente cero', ONE_ONLY: 'Exactamente uno', ZERO_OR_MORE: 'Cero o más', ONE_OR_MORE: 'Uno o más', ALL: 'Todos' }
  } },
  en: { editor: {
    loading: 'Loading configuration…', loadError: 'Could not load the configuration.', backValidators: 'Validators', backTransformers: 'Transformers', create: 'Create {{kind}}', edit: 'Edit {{kind}}', configurationData: 'Configuration data', metadataHint: 'Saved independently from rules.', rules: 'Rules', ruleCount: '{{count}} rule', ruleCount_plural: '{{count}} rules', editOneRule: 'edit one rule at a time.', addRule: 'Add rule', name: 'Name', description: 'Description', type: 'Type', mandatory: 'Mandatory', quantifier: 'Quantifier', order: 'Order', actions: 'Actions', unnamed: 'Unnamed', incomplete: 'Incomplete configuration', unavailableType: 'Unavailable type', yes: 'Yes', no: 'No', moveUp: 'Move up', moveDown: 'Move down', editRule: 'Edit rule', deleteRule: 'Delete rule', noRules: 'There are no rules yet. Add the first rule to configure it.', cancel: 'Cancel', saveConfiguration: 'Save configuration', close: 'Close', newRule: 'New rule', individualRule: 'Individual configuration for rule {{number}}', remove: 'Remove', specificConfiguration: 'Specific configuration: {{name}}', typeUnavailable: 'This rule type is unavailable in the active engine. Select one of the published types to continue.', saveRule: 'Save this rule', saveFirst: 'Save the {{kind}} first to save rules individually.', deleteTitle: 'Delete this rule?', deleteWarning: 'The rule will no longer belong to this {{kind}}. This action cannot be undone.', savedConfiguration: 'The {{kind}} was saved successfully.', savedRule: 'Rule “{{name}}” was saved successfully.', deletedRule: 'The rule was deleted successfully.', reorderedRules: 'The rule order was updated successfully.', incompleteRule: 'Select a type and enter a name.', quantifiers: { ZERO_ONLY: 'Exactly zero', ONE_ONLY: 'Exactly one', ZERO_OR_MORE: 'Zero or more', ONE_OR_MORE: 'One or more', ALL: 'All' }
  } },
  pt: { editor: {
    loading: 'Carregando configuração…', loadError: 'Não foi possível carregar a configuração.', backValidators: 'Validadores', backTransformers: 'Transformadores', create: 'Criar {{kind}}', edit: 'Editar {{kind}}', configurationData: 'Dados da configuração', metadataHint: 'São salvos independentemente das regras.', rules: 'Regras', ruleCount: '{{count}} regra', ruleCount_plural: '{{count}} regras', editOneRule: 'edite uma regra por vez.', addRule: 'Adicionar regra', name: 'Nome', description: 'Descrição', type: 'Tipo', mandatory: 'Obrigatória', quantifier: 'Quantificador', order: 'Ordem', actions: 'Ações', unnamed: 'Sem nome', incomplete: 'Configuração incompleta', unavailableType: 'Tipo indisponível', yes: 'Sim', no: 'Não', moveUp: 'Subir', moveDown: 'Descer', editRule: 'Editar regra', deleteRule: 'Excluir regra', noRules: 'Ainda não há regras. Adicione a primeira regra para configurá-la.', cancel: 'Cancelar', saveConfiguration: 'Salvar configuração', close: 'Fechar', newRule: 'Nova regra', individualRule: 'Configuração individual da regra {{number}}', remove: 'Remover', specificConfiguration: 'Configuração específica: {{name}}', typeUnavailable: 'Este tipo de regra não está disponível no motor ativo. Selecione um dos tipos publicados para continuar.', saveRule: 'Salvar esta regra', saveFirst: 'Salve primeiro o {{kind}} para salvar regras individualmente.', deleteTitle: 'Excluir esta regra?', deleteWarning: 'A regra deixará de fazer parte deste {{kind}}. Esta ação não pode ser desfeita.', savedConfiguration: 'O {{kind}} foi salvo com sucesso.', savedRule: 'A regra “{{name}}” foi salva com sucesso.', deletedRule: 'A regra foi excluída com sucesso.', reorderedRules: 'A ordem das regras foi atualizada com sucesso.', incompleteRule: 'Selecione um tipo e informe um nome.', quantifiers: { ZERO_ONLY: 'Exatamente zero', ONE_ONLY: 'Exatamente uma', ZERO_OR_MORE: 'Zero ou mais', ONE_OR_MORE: 'Uma ou mais', ALL: 'Todas' }
  } },
} as const

for (const [language, bundle] of Object.entries(resources)) i18n.addResourceBundle(language, 'translation', { configurationEditor: bundle.editor }, true, true)
